spring.application.name=metro
spring.datasource.url=jdbc:mysql://localhost:3306/namma_metro
spring.datasource.username=root
spring.datasource.password=Brin@675

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080